# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Area.create(name:'銀座・新橋・有楽町')
Area.create(name:'池袋')
Area.create(name:'原宿・表参道・青山')
Area.create(name:'浜松町・田町・品川')
Area.create(name:'渋谷・恵比寿・代官山')
Area.create(name:'六本木・麻布・広尾')
Area.create(name:'上野・浅草・日暮里')
Area.create(name:'新宿・代々木・大久保')
Area.create(name:'赤坂・永田町・溜池')
Area.create(name:'目黒・白金・五反田')
Area.create(name:'吉祥寺・三鷹')
Area.create(name:'町田・稲城')
Genre.create(name:'焼肉')
Genre.create(name:'寿司')
Genre.create(name:'居酒屋')
Genre.create(name:'イタリアン')
Genre.create(name:'中華料理')
Genre.create(name:'カフェ')
Genre.create(name:'和食')
Genre.create(name:'フレンチ')
Genre.create(name:'韓国料理')
Genre.create(name:'スイーツ')
Scene.create(name:'初デート')
Scene.create(name:'彼女の誕生日')
Scene.create(name:'記念日')
Scene.create(name:'合コン')
Feature.create(name:'初デートにオススメ')
Feature.create(name:'お手頃だけどお洒落')
Feature.create(name:'お手頃なイタリアン')
Feature.create(name:'個室がある')
Feature.create(name:'学生にオススメ')
Feature.create(name:'カップルシートがある')
Feature.create(name:'お洒落な空間')
Feature.create(name:'喫煙可')
Feature.create(name:'夜景がキレイ')
