# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Genre.create(name:'焼肉')
Genre.create(name:'寿司')
Genre.create(name:'居酒屋')
Genre.create(name:'イタリアン')
Genre.create(name:'中華料理')
Genre.create(name:'カフェ')
Genre.create(name:'和食')
Genre.create(name:'フレンチ')
Genre.create(name:'韓国料理')
Genre.create(name:'スイーツ')
Scene.create(name:'初デート')
Scene.create(name:'彼女の誕生日')
Scene.create(name:'記念日')
Scene.create(name:'合コン')
Feature.create(name:'初デートにオススメ')
Feature.create(name:'お手頃だけどお洒落')
Feature.create(name:'お手頃なイタリアン')
Feature.create(name:'個室がある')
Feature.create(name:'学生にオススメ')
Feature.create(name:'カップルシートがある')
Feature.create(name:'お洒落な空間')
Feature.create(name:'喫煙可')
Feature.create(name:'夜景がキレイ')
Restaurant.create(name:'あああ', name_alias:'あああ', tel:'00000000', about:'ああああ', prefecture:'あああ', city_address:'あああ', building_name:'あああ', genre_id:'1', scene_id:'1', feature_id:'1')
Restaurant.create(name:'いいい', name_alias:'いいい', tel:'000000000', about:'いいいい', prefecture:'いいい', city_address:'いいい', building_name:'いいい', genre_id:'２', scene_id:'２', feature_id:'２')
Restaurant.create(name:'ううう', name_alias:'ううう', tel:'00000000', about:'いいい', prefecture:'いいい', city_address:'いいい', building_name:'ううう', genre_id:'3', scene_id:'3', feature_id:'3')
Restaurant.create(name:'えええ', name_alias:'えええ', tel:'000000000', about:'えええ', prefecture:'えええ', city_address:'えええ', building_name:'えええ', genre_id:'4', scene_id:'4', feature_id:'4')
Restaurant.create(name:'おおお', name_alias:'おおお', tel:'000000000', about:'おおお', prefecture:'おおお', city_address:'おおお', building_name:'おおお', genre_id:'５', scene_id:'5', feature_id:'5')
